### ISSUE TITLE
rotorParams.h help

### ISSUE THREAD

**Issue by giordyb** [ajohns1288/AzElTracker#1]
Hi, I built my own rotor based on this https://www.sarcnet.org/rotator-mk2.html and I would like to use your code since I'm using stepper motors.
Can you please explain how to calculate the az/el steps per degree and az/el degrees per step found in rootParams.h?

I've done some tests and it takes me 9750 micro steps per complete rotation.
Thanks!

**Comment by ajohns1288** [comment]
There are two ways you can do it. The first is to take the degrees per step for the motor (usually 1.8 degrees for a 200 step/rev motor) and multiply it by the gear ratio. In my case, it was 1.8*(1/4.1) which gives 0.43 steps per degree. The code uses degrees*100 to avoid having to use floats so 0.43 is represented by 43. 

The second method is to count how many pulses of the step line it takes to complete one rotation and divide that by 360 to get steps per degree. 

As both are inverses of each other, once you have one, you can calculate the other by taking the inverse (1/x). In this case, if I did the math correctly, it should be 9750/360 to get 27.08 steps per degree, 1/27.08 is .037 degrees per step which would be input into the code as 4 (.037*100 rounded to nearest integer).

Let me know if that works.

**Comment by giordyb** [comment]
Hi @ajohns1288  thanks for the quick reply! I'm actually using some pulleys so it's a bit hard to calculate the actual number of steps. What I did is write some code and see how many times I have to activate the step pin to do a full rotation:

```
void rotate (int Delay, int Rotation, int Direction){
  //digitalWrite(enablePin, LOW);                 
  if (Direction == 1) {
      Serial.println("UP");
      digitalWrite(dirPin, LOW);
      RotTotal = RotTotal + Rotation;
    }
    else {
      Serial.println("DOWN");
      digitalWrite(dirPin, HIGH);
      RotTotal = RotTotal - Rotation;
    }
  for (int i = 0; i < Rotation; i++){
    Serial.println(i); 
    digitalWrite(stepPin, HIGH);   
    digitalWrite(stepPin, LOW); 
 
  }
  Serial.println(String("rotating ") + Rotation + String(" dir ") + Direction );    
  //digitalWrite(enablePin, HIGH);                 
  
}
```

this is how I came up with 9750.

now if I do 9750/36000 I get 27.08 but if I put that number in as the degrees per step I'm way off. I tried a few numbers and I'm actually closer to 4.75 and I'd like to understand why... do you have any hints that you can give me?

I also noticed that AZ_STEPS_PER_DEG and EL_STEPS_PER_DEG are not used anywhere in the code.

**Comment by giordyb** [comment]
OK thank you what you are saying now it makes sense! Just FYI I noticed that the *_STEPS_PER_DEG is not used anywhere in the code.
Another question: the stepping is really slow although I don't see any delay() in your code...is there anywhere that I can look to make it faster?

**Comment by giordyb** [comment]
Nevermind I just figured out I had to move it up in the timer. Everything works great! thank you!

**Comment by ajohns1288** [comment]
Just in case anyone else reads this, the step routine is ran in a 5ms or 20ms loop, depending on the axis. If your gear ratio is really large, you may need to make the timer execute faster to get more steps per second. There is also a speed command which will cause the step to only actuate from every loop to every 3 loops for use during runtime.

As giordyb mentioned, *_STEPS_PER_DEG is not used in the code. I added this to future proof the program in case the inverse was ever needed. The constant is to avoid doing a 1/x for DEG_PER_STEP.
